management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true  
      
  endpoints:
    web:
      exposure:
        include:
        - "*"
logging:
  file:
    name: e://logs//config-client.log
